repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.27.0
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
